stages:
  - prepare1
  - prepare2
  - build
  - patch
  - pack
  - deploy
  
variables:
  GIT_DEPTH: "1"

cache:
  paths:
    - Library/
    - Temp/

get_data:
  stage: prepare1
  tags:
    - linux
  dependencies: []
  artifacts:
    paths:
      - ygopro2-data/cdb
  script:
    - mkdir -p ygopro2-data/cdb
    - wget -O ygopro2-data/cdb/cards.cdb https://cdn01.moecube.com/koishipro/contents/cards.cdb
    - wget -O ygopro2-data/cdb/lflist.conf https://cdn01.moecube.com/koishipro/contents/lflist.conf
    - wget -O ygopro2-data/cdb/strings.conf https://cdn01.moecube.com/koishipro/contents/strings.conf

make_data_archive:
  stage: prepare2
  tags:
    - macos
  dependencies:
    - get_data
  artifacts:
    paths:
      - Assets/StreamingAssets/ygopro2-data.zip
  script:
    - cd ygopro2-data
    - zip -r ../Assets/StreamingAssets/ygopro2-data.zip *
    - cd ..

unity:
  stage: build
  script: cmd /C .gitlab-ci.bat
  dependencies:
    - make_data_archive
  artifacts:
    paths:
      - dist/
  tags:
    - unity

patch-header:
  stage: patch
  dependencies:
    - unity
  script:
    - apt update; apt -y install tar patch
    - mv dist/src ./unity-src
    - cd unity-src
    - chmod +x *.sh
    - sed -i '/>UIStatusBarStyle</i\    <key>UIFileSharingEnabled</key>\n    <true />\n    <key>LSSupportsOpeningDocumentsInPlace</key>\n    <true />' ./Info.plist
    - patch -p1 < ../misc/patches/iPhone_Sensors.mm.patch
    - echo '#define UNITY_USES_LOCATION 0' >> ./Classes/Preprocessor.h
    - sed -i 's/^#define UNITY_USES_REMOTE_NOTIFICATIONS 1/#define UNITY_USES_REMOTE_NOTIFICATIONS 0/g' ./Classes/Preprocessor.h
    - rm -rf Libraries
    - cd ..
  artifacts:
    paths:
      - unity-src/
  tags:
    - linux

patch-lib:
  stage: patch
  dependencies:
    - unity
  script:
    - mkdir unity-src
    - cd unity-src
    - mv ../dist/src/Libraries .
    - env MISC_PATH="../misc" ../patches.sh
    - cd ..
  artifacts:
    paths:
      - unity-src/
  tags:
    - macos

pack:
  stage: pack
  dependencies:
    - patch-header
    - patch-lib
  script:
    - mkdir dist
    - cd unity-src
    - tar zcvf ../dist/KoishiPro2-src.tar.gz *
    - cd ..
  artifacts:
    paths:
      - dist/
  tags:
    - linux

upload_to_minio_latest:
  stage: deploy
  dependencies:
    - pack
  tags: 
    - linux
  image: python
  script:
    - pip install -U awscli
    - aws s3 --endpoint=https://minio.mycard.moe:9000 sync --delete dist/ s3://mycard/koishipro2/latest
  only:
    - Android
    #- tags

upload_to_minio_tag:
  stage: deploy
  dependencies:
    - pack
  tags: 
    - linux
  image: python
  script:
    - pip install -U awscli
    - aws s3 --endpoint=https://minio.mycard.moe:9000 sync --delete dist/ s3://mycard/koishipro2/$CI_COMMIT_TAG
  only:
    - tags
