stages:
  - build
  
variables:
  GIT_DEPTH: "1"

cache:
  paths:
    - Library/
    - Temp/

ios:
  stage: build
  script: cmd /C .gitlab-ci.bat
  #artifacts:
  #  paths:
  #    - dist/

  only:
    - Android
  tags:
    - unity
